CREATE DATABASE IF NOT EXISTS HEALTHCARE_DW;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DW.BRONZE;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DW.SILVER;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DW.GOLD;

USE DATABASE HEALTHCARE_DW;
USE SCHEMA GOLD;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('', 'NULL', 'None')
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- Replace bucket name before running.
CREATE OR REPLACE STAGE HEALTHCARE_SILVER_STAGE
URL = 's3://your-healthcare-etl-bucket/silver/healthcare/'
FILE_FORMAT = CSV_FORMAT;
