USE DATABASE HEALTHCARE_DW;
USE SCHEMA GOLD;

COPY INTO dim_patient
FROM @HEALTHCARE_SILVER_STAGE/dim_patient.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO dim_doctor
FROM @HEALTHCARE_SILVER_STAGE/dim_doctor.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO dim_appointment
FROM @HEALTHCARE_SILVER_STAGE/dim_appointment.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO fact_treatment
FROM @HEALTHCARE_SILVER_STAGE/fact_treatment.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
